update templates to parametrize hpa options

diff --git a/my-helm/templates/loadgenerator/deployment.yaml b/my-helm/templates/loadgenerator/deployment.yaml
--- a/my-helm/templates/loadgenerator/deployment.yaml
+++ b/my-helm/templates/loadgenerator/deployment.yaml
@@ -26,37 +26,37 @@ spec:
         - name: {{ .Values.global.imagePullSecretName }}
       restartPolicy: Always
       terminationGracePeriodSeconds: 5
-      initContainers:
-      - name: {{ .Values.loadgenerator.name }}-check
-        securityContext:
-          allowPrivilegeEscalation: false
-          capabilities:
-            drop:
-              - ALL
-          privileged: false
-          readOnlyRootFilesystem: true
-        image: busybox:latest
-        env:
-        - name: FRONTEND_ADDR
-          value: "frontend:80"
-        command:
-        - /bin/sh
-        - -exc
-        - |
-          MAX_RETRIES=12
-          RETRY_INTERVAL=10
-          for i in $(seq 1 $MAX_RETRIES); do
-            echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
-            STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
-            if [ $STATUSCODE -eq 200 ]; then
-                echo "Frontend is reachable."
-                exit 0
-            fi
-            echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
-            sleep $RETRY_INTERVAL
-          done
-          echo "Failed to reach frontend after $MAX_RETRIES attempts."
-          exit 1
+      # initContainers:
+      # - name: {{ .Values.loadgenerator.name }}-check
+      #   securityContext:
+      #     allowPrivilegeEscalation: false
+      #     capabilities:
+      #       drop:
+      #         - ALL
+      #     privileged: false
+      #     readOnlyRootFilesystem: true
+      #   image: busybox:latest
+      #   env:
+      #   - name: FRONTEND_ADDR
+      #     value: "frontend:80"
+      #   command:
+      #   - /bin/sh
+      #   - -exc
+      #   - |
+      #     MAX_RETRIES=12
+      #     RETRY_INTERVAL=10
+      #     for i in $(seq 1 $MAX_RETRIES); do
+      #       echo "Attempt $i: Pinging frontend: ${FRONTEND_ADDR}..."
+      #       STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
+      #       if [ $STATUSCODE -eq 200 ]; then
+      #           echo "Frontend is reachable."
+      #           exit 0
+      #       fi
+      #       echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
+      #       sleep $RETRY_INTERVAL
+      #     done
+      #     echo "Failed to reach frontend after $MAX_RETRIES attempts."
+      #     exit 1
       containers:
         - name: {{ .Values.loadgenerator.name }}
           image: "{{ .Values.loadgenerator.image.repository }}:{{ .Values.loadgenerator.image.tag }}"
